apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jS7OTyZhGVDuURMElGDrq/2uoQrg9JiV1dkbcZOLEOCX+XuD,iv:P0uKwNPQZdxzigwN75CBApjUw/VsFgn4mBy4++YJFAo=,tag:KXnq82CRL3JOp9SHhnhUiA==,type:str]
    credentials.json: ENC[AES256_GCM,data:gr0M6vN9F0EJqWQWdIuB8QlDz92T77cX14Eep2M6Cn4FN38qiaNEPQLRCyHRUDdb+JPbu+LwNHTm5pjaVDvYBLy8r62rJYPCLbq/Ir50+UWIKOCWfnimzKoZPCsmWqh5j+DGrEsGhzJJMaHpOf66YOcWeb34VXdJmBsLHPuhpnmzJQwW05LLi7+U7LTpQez/GXT2TLmFp9L6dCh1t5nmeGpreKXyBgpUgvI5eKCjnQ==,iv:eL7NfQe4Me6Zghl6+ORxXhARVUg3Ol5z3Q5QPP6J+Sk=,tag:NlIdCd0UaHjynzRml/0NTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VkhKL1NabEZHWS9QTDFq
            ZHRUaVpHU2d2ZVIwRkswZGEyb1cyYVBtbG04CmFUemdnQWlmc1hUSHNrVkdUcnoz
            bjRWb3h4c0psQ2hyNzArRzRidnVrOWMKLS0tIHc2V0RBV3NOYmtJOG1adFBIOFJ4
            ajl5NEFGOEs2RUxKQzBBTDNia05NYTgKdpw5Vn0sBL9M93TGWZ27/XFLRyq5Edow
            +3P4I2I0qXHZ3u/CJ1DFW/F24hsA+GZKDJKbm1j4pJG6dRz5KfVnYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T19:37:21Z"
    mac: ENC[AES256_GCM,data:STKt6U3J/UbRs2fMsDTQtcQaLI1G0af+qA8cV/M8jkO+iXc7QT4BDll1zlTQAkFvqw6bDn1o8Tc5fWXMNbgA61ESPx9DeU1dZbBIP7/SsgPbMXPv5dLAPKKQo9554QqHnivqIj/GmI3RT883UWYmENurcCMt3QiPwA/iaLop9Nk=,iv:d7bYMP9N/xiThDGBeP5uo/9VDj64hXl4CFdecV0nlAI=,tag:SmArel3BiuvhvcmfPkNWew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
