---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_DATABASE_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_DATABASE_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__HOST: postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: authentik
        AUTHENTIK_EMAIL__HOST: smtp.office365.com
        AUTHENTIK_EMAIL__PORT: "587"
        AUTHENTIK_EMAIL__USE_TLS: "true"
        AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_REDIS__PASSWORD: "{{ .AUTHENTIK_REDIS_PASSWORD }}"
        AUTHENTIK_REDIS__HOST: "{{ .AUTHENTIK_REDIS_HOST }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: authentik
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
