apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Gnda7TY7S9URWeOq2VMbV4eFE0Br43ShPuYTHdfgQrnUVN8sFLtBmw==,iv:fdTUxLOkjFdK1E8liIbNhVZPHybOAf1g2eXYonDM6/8=,tag:ncPAky7FMqcarDKtseXWmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcXJRZUtRT0d5TklTTHVy
            NzdzQ3BrVmQ4VHBvRmQvWGdxNlVoMWVSbUhVCnRFV2oycmhaQ05wdzBSWXZicjFY
            d1IyUWpXYVBNUjJNSWc4Vm5BY0xJQjgKLS0tIGJNcGZJNEkwNGJEV3FmekZYQk1D
            M3N4aEZNU2k3cjIwdi90ODdHRE1Kc1UKIaKdqkS9e3rTY4QnV65wc5NSnLBvq2CR
            G9Q/x9ba0QRN4MmEiRJKF8WqDbxKLFNaoH8eaWqpGBoG7t68EDEJ5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T13:13:05Z"
    mac: ENC[AES256_GCM,data:7L8cpLomTHRUv9HZnvzbYvIuv6gDwXBnsJPKawOT/RgucXEupiuFejNPbDUtBYOHNrU7wRpp2RL8aVZT2iVo/HZJAuL2tjMKpjmj8MzQY2pv4lrxwalGfeWc6KNoyjK/IU6WiCVz2YMvg922hmFBfNG1W1qHc9hflHQ/rDix10M=,iv:CZ90FvcIn8TGswqyEll4M34ICiFhOGBolEhClLZmyz0=,tag:5axfboSmfz6z48l1uEHPsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
