apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YVmeSuTyy4cyVjSknZeP4cSNOmQeyiWin1KLCVIpYUMXl1J1o//riQ==,iv:6rfJfr6QMHEF1+Gnz7fYWFq+qJ9+eC11hYcfBbn3+Bw=,tag:BABBKLyrBN3eV9rKw7t/AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraHZsT0QraWJEOWtHbEpm
            U045M3FGZFRETG8wYk9oZkNtbkxDNURwU1ZVCkpZWXF2ZFNVVWV0L2hGM1V6dTgz
            ZElPdkZkSDhjTmxWeld5TVRXVjVoM0kKLS0tIGNwZVNBNlpuVDZDYTJuV0hMZGpS
            MDJ5WGxmbnNta2VFR2JlTkN2ZjVIelkKpzUfEmueljQrrThxs2PjHZspB1fPR66L
            4cAfMZWKbg+PQbIDUb0AUVI48zu4kmYi1gwZnsV6G37ciilSFU0XPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T19:37:21Z"
    mac: ENC[AES256_GCM,data:BS8HEZVcAYPx/sl4aGfcF3DKZQD7Y1jIH4jhgeFKaFykp6LGsTP1BGQCMf8anpP8R9ZAZeR9MhggN3UAJkfgKUlwNUPWlcKsK1k/34KE264/SeSTMQlthOzVjzAWDUtp9cF5uIRRMeDtQBzcuSLswqD0C2VNlLe+24PqOmUzjDg=,iv:vWnjMKcfwgGOCMvYKbl9bMLEMS1D+kIMq5WzGZTMqPg=,tag:IMxBAKViaHexLnjFFxsZ4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
