apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:X7n4tElaYwoNczkD5VFMkHUQn+tSj9eFTk8oKIlzZ2jFjDPm0oJoUQ==,iv:jW6Z31kJcxaRK4I1FKvNevOwFs5+pIkjhmk7OZQxyGI=,tag:AsMuo2orjxJv87dyl5nbiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWG5BTGRwb1ZTNnJYNXdS
            bmlXVG42eTVXMHZYZjFqdFNlakprRmc1dlRFCkxSRFdQNmRITnVSNlNSa2FvSlM4
            Q1pHQ1dRdks4djZBTmNoSEVtREFEL28KLS0tIHJaM3VYa29SMTRoOXFNaHJROVly
            RlVjRWdpb2x2dTExOE9yVUsrNmtIRmMKHyYne6u5dMIUrYP9priKKbQaG9+jSKdg
            /VH4JExSsKrHIldm9lvwutsLLAKXIDE0TIdA1MtcK2LzOr3MgnjmbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T10:06:49Z"
    mac: ENC[AES256_GCM,data:OinOt/LJ/aoBOxh5lTju83QXvDuwrUecOlnNfS9DHL6i7igoawe85l0c0ueJ9wsatVb/6PfNu25GSpZoJ1+POz1cE3AgRnr82YmKOSGZ6pDAdeeUxLhdj2yYpv4ebuPkWFUK4mWnEPmF//qEHRTVNbCiAsiYal4CwOnIIRwaAas=,iv:dyni8nPhXvFHZFu1ispJN0/x5oTVndM6RpwOK0LmpLA=,tag:8K/3VBwMEuCJNn3oHIeOEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
