apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:7W+1vHIQT6tSo3aDcU5lAqSydjC8CS2RfZlOzxpLNaLWYJaY+h/HLq9YImQr/NvBMYzQm0zX+I4LTSWdtFvpGpukaa0NniivMgEmtSUyoV6wlmdISG1wK51fQMCLCA==,iv:3IN+nPfiIA6KJCkOenXMEcGhOlIIG4VdolKukvb0wpM=,tag:n+zZQvWTgXfgUahImA9hKw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZlkQwXtwP6b92Hc=,iv:0ZuOzV3xu8RdnifA+pUZRhMnvEoc/vcR4NTld/LIA14=,tag:o4A48cl28/6boPHL1LIpyA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JTKT4nIT5JcFi5kByAhFcHhWKyuooz4lMQ==,iv:sXPTw7V6S4KmUWLm+cW5WxokxxfCw9B3brMF8j+e8bo=,tag:j3GW4SqFowbbWksKixDYkg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:z1M3D6GDbcMT2VUTrFOyJcfxWxp4BeZktIv55U7BD4ZQ6+t1,iv:AsNZABBiPilsvbaHDbI3Qt5MjRoH4/ml80IXjlmCTcI=,tag:ADLav2ojHPprrqJjm1yZmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRDNrYXgrQnlRQmx1NklY
            YXQ4bElrdjJOMndFMnlQUUtWNEhvSlQ0SFU4CnpYWHltcDEweG5xWmxoOW83UVov
            dnZXV2FPMkpoVFFUN0FLZW9jVEp0UVUKLS0tIGRxV0ZHK3U2elMwMEo0NE16T01M
            cW5ZQ1lZZzNJd28rUTkxM0dnY09mazAKasf/2g3eO/5o1f4YGFXr71Jy7DhPLOc4
            dJpOD7lEFxIFNiAm/NnXurReVtRoDN4cnrSQCS+Vgxn2aWm7+sKV+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T14:23:24Z"
    mac: ENC[AES256_GCM,data:GP9gfLsTgg7XygwZZIZjg3pZgGyWLM9f/y2IWvOjfh2N+kPEehR2PxjX/O40QkFljssI1/hRieOGKXwbbTT4/jb6svpg5RNWuCY0VApEJGJVNckOkOeIS1zez3uhYLUhQQgj27IaGhYTNLvk7orrst9unxkp1dUHpJFuYyDqQow=,iv:U6T8AZLgFxKmURxy/Q0ofQfRUYiX1vIpIXOThfnq+d8=,tag:U/mLOKMdYt/Pdwn+DM4Xdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
