apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ZzpkRyauMlcWcaB+B+EBsCsudK362LD+i+rqFdksp+k=,iv:NVP5AcJ5tPVZo3nU59C5y+clYEbxvw7LHQ1qWcm0ohg=,tag:9WNjQwjIR/MJf89WVrE+bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SHdPWWZJYy9DWlNpdmV5
            REovT2pwcmpmRWNNTmdtZzVRcVd1OUJsaEFNClhaQkhFaGgzbDdKM0pGT3JNVmE2
            d3B0R0YrQXFTdE05dmZDZTB4VGE5SVUKLS0tIFAyTER3a3lyQ0UwKzRPM0g5VWdq
            YzVKa2lpL3hnVllSVGxUdW1zeG9BcXcKqPOlxDIr5gOCeZuDNgDHiJPuwfZk8J4M
            ZTOuzLWu88hwBrx15ukHf8WwzQ3crNqBF9XMX8iPXyXjmBzcdgmvyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T19:06:01Z"
    mac: ENC[AES256_GCM,data:b2QF3UNMzxfgaSJvmWil+G3uv1ZUeOvtYL2dvnqpP6S98XyMz5sXo1qC+EtLyvWHAVFn/Qn3yD/x5XJi6pFl4zbOux3uXllnOHP1d6JYX6vSuwfLjjgdDxary85DdLy5ao2axt8dRCIbJALo/Tv4nAXs0WpFX1FinT4uzURcuPg=,iv:BDCpfpDEihQPvl66VLGJDL9RSaWYr9l0pvDZF55dNvM=,tag:cTAhTd12xeIjsG9LenggBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
