apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xx6evjRekOQD/GiEg9+pkmX3VGePfYHyCnovO9AAVjM=,iv:wXM0sMRVZGgpA5hwt8SZN5mCGQ0HfLtXZ6UTlQ/ExXo=,tag:ZhHrVBjdADCoMU5cHkpx7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y1VubUljQzVBMGR2UjVt
            cSsrYmY2amVCeW01Sk00RktKVzVBOVNpb3dRCkN3YkJ1MTFtQXVTaVZ2S01NNUZx
            eDBrbEhzUVNBYU9lbjVxejdyWjdUV1UKLS0tIFdGVCs3NFlIQ3dIZWxNL0JsRGpn
            T3BFWDFMc3VZNjdlWS9IbnZod1JHUXcKm0GbDn2JwcedL+HAUmaCXpC40RuUm2a5
            FN172vzItfQ46lAL712wDPlXXjQzH1wkr+CtY1iB2hjcW7HkN2vEaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T13:13:05Z"
    mac: ENC[AES256_GCM,data:O/WmhnIbcme0PlWjKaTYZIVB4ws+t6y/o+eyes26Qy6GhLrKMwCcuUZbizApRqcc6kNQY5UrgGFxBEAmGSLsAg0M7WSM0NqzovGS+oVKK2YF0n9DbGx4vO5zxlg8aeHmZu00Ep3+H2WpaY7Dqt3xeZm6qrzV9aD8eZ6yR0iwqR4=,iv:fN3Ynk9784msWA7ZqG7QaYaOBWRf2pWAxEs9LgtpCNs=,tag:1bUlPQEu4NaK8w2EHO1AQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
