apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:y2dRkJkMLLOtMkE0UNRsBNvs3yAMgatgoR7Apb76Z2wBMWeTncISIQ==,iv:xyGMpN3z7Z5rXBUAj+nALTh6onIyrsBHOSu7L8rsQDw=,tag:URDOzAozHhiR7V7o22auVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ky9icXRaaitNc1FUYklo
            TnZaOWtVaWsvYVZzR1BwQmVkOUYwVkJvR0NJClJRUFc1cmFXZW9ZZ3ltRkc3YUJD
            Nm9UZzl6bjFLKzkzK3VVNHFmZ2FWdDgKLS0tIE9ybnlIbi91MFJrc1FhUDYzSCt2
            Q2wxRGNSUWRjTE81ZFNlUndJNkU1WGMKurtrhjjlVxvEZiX9j0bob58YorXubjCW
            c4puzqjDqJSztQE5IlLiygha6DRlYIZXxxfbVaRzQwuDavL2zhd+hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T10:02:46Z"
    mac: ENC[AES256_GCM,data:7dsGvnnmtonepvTUBKMvrwjVtYY51pTZsKtekobwojQYTNOS8h5yVoVVdE1KeS0KACW+6T52dsTp9YCXl0XZ4IcbMC1Xu/OIpMrX450mEfaKcWf0kbHRVLlQVr38StxwvmUWuckHNsUe/sM/VUJhSbv+SbNGHPYOf/q8Yj9zM7U=,iv:JezNJiLveaT+Nj35a9ZaYN2AZnHyIvTQpkEq3x9p/14=,tag:TOr53z4Pa6UrVPskWhiMkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
