apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZVZ5X+gd9K5KSJ42hG2TAkcvsz31iArm1ejhj78drrAPJi78s3MM7Q==,iv:wXmDqTpF1GGFveJAdaGq88wYSOnVofzJ+wOe4Xj+gnM=,tag:FBuABR3uIdff4GlfuuF6yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVWtFQjA4b3V6blo3aHFa
            NmxGSXpmTGxsbjkxWnVTYis0aXZ4VmZWZWlBCkNWZGRuOW9QODVtbEdkNGo0TW1H
            SGpVRjcxTXZvd1kvb0dGcGN5cUcvYk0KLS0tIGRSVW03N0RJVzlsQWtaaUx4d3p6
            WUZMcEpwMHUzMlhpcW5BRTQyTWhTUmcKM1k+4af1Ni1e48std+iOalzEJgZ5ZRp9
            b7Efhwca4PHRM9cJXLsDjQp4cMMLvNH9Ek4JJfB1qtM4udQmnpTNnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T14:23:24Z"
    mac: ENC[AES256_GCM,data:ZSPXn8RZlC8wSmhfuPIibccPY7u7XDCkB0gX6i1wVpDeEvb9KYx0Qf0HeYnBNiy5RnkkejXelIEyxZJ1FsjpTzONh6f/jbN+HFAt6ShFYaMk22TXl0fwyhxd3ESxtBzqNWSms0E8tCGP2Agc3mWdfPtB9JuZnY8SYnfhKTlfYfI=,iv:LIQVwH7LT1PMe5Xptee8J8T/A0AiRATdi9h3YVZGc5c=,tag:dj81TDTRMY6NME0Ge1Q1Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
