apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:q71BFgAw+AMB1SUYgNvEwd53iV3B5xuPeQT7ch///8sip0B4Klbz3Q==,iv:gD555Xa2FpwDWbjsnK0pDThHCftVQEZTgkY10IphRao=,tag:7pA78oT6IsyDPLOspVRdvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xazl2wunxgnzszcmh8prfcppml7jacuh294thqwk8jv70ftv8slqqe8g27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOGgzWXFJN3ZYOVJLU2xJ
            bEYzZElhTldEZWg2L2J3TGtWMGQxUEx1QnprCkhpdFFrRVgvRy9PMkFwUHJpWFU1
            aS9vd0M3SkpJTDh5dFN4UUdhdEdjYkkKLS0tIHNRV3FHU3o4elJPYnU0Ujd6WU5N
            WWxQNUY3bkl4QVJHMzcxc2U0M05mTDAKjP0iRe5y/0P62oPApWFZVry+3QN2Runb
            e7oHR5rvKK4j2jN0pKcMl3A4n8qi47s6BfzSF2RQyTT7eDTuY9KZjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T13:13:05Z"
    mac: ENC[AES256_GCM,data:y3kgVWTllbCWY2bYjhm070FfUH4onqHrz3aVc8npmh67PwRL+GVh1JefjzRRKEv8at7Ljr32D1TgPtataNpx0YR/ivkDLqVLbPuDxxTCoxcTRopDtZ+Mme0Ue3OXw88PianVMDQQP6S9CFIwEJQXaDchLtsXngupeJcENe/TfsM=,iv:1HignJWYjajC34W1u+aReFpsAJuD2ZHsZPzbkFs+Dlo=,tag:Wiik0ucQ4XiiWfAjk1gbAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
